drop table quotes if exists
drop table categories if exists
drop table projects if exists

CREATE TABLE quotes (id bigint generated by default as identity (start with 1), text varchar(255), author varchar(255), primary key (id))
CREATE TABLE categories (id bigint generated by default as identity (start with 1), name varchar(255), primary key (id))
CREATE TABLE projects (id bigint generated by default as identity (start with 1), name varchar(255),category_id BIGINT, theEndDay integer, link varchar(255), description varchar(255), short_description varchar(255), history varchar(255),pledged double ,goal double,status integer, primary key (id) )
 